'use client'

/** STYLE: panneau Super Admin compact ; hiérarchie opérationnelle sombre et repères DEMO explicites. */
import Link from 'next/link'
import { Activity, AlertTriangle, ArrowRight, Database, FileBarChart, RefreshCw, Scale, ShieldCheck, WalletCards } from 'lucide-react'
import { usePilotDemo } from '@/lib/supabase/usePilotDemo'
import { PilotDataBadge } from './PilotDataBadge'

const money = (amount: number) => new Intl.NumberFormat('fr-CA', { style: 'currency', currency: 'CAD' }).format(amount)
const clean = (value: string) => value.replace(/^DEMO[-_]/, '').replaceAll('_', ' ')
const chip = (value: string) => /MATCHED|READY|COMPLETED|ACTIVE|ONLINE|VALID|RECEIVED|PAID/.test(value) ? 'border-emerald-400/25 bg-emerald-500/15 text-emerald-300' : /REVIEW|PARTIAL|PENDING|WARNING|FIRING|MISMATCH/.test(value) ? 'border-amber-400/25 bg-amber-500/15 text-amber-200' : 'border-slate-600 bg-slate-700 text-slate-300'

export function PilotScenarioOverview({ compact = false }: { compact?: boolean }) {
  const { data, loading, error, refresh } = usePilotDemo()
  if (loading) return <div className="flex min-h-48 items-center justify-center text-xs text-slate-400"><RefreshCw className="mr-2 animate-spin text-qc-blue" size={16}/>Chargement du scénario pilote…</div>
  if (error || !data) return <div className="rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-xs text-red-200"><AlertTriangle className="mb-2" size={17}/>{error ?? 'Scénario pilote indisponible.'}<button onClick={() => void refresh()} className="ml-3 underline">Réessayer</button></div>

  const measures = compact ? [
    ['Chauffeurs', data.metrics.drivers, 'text-blue-300'], ['Activités', data.metrics.activities, 'text-sky-300'], ['Revenus nets', money(data.metrics.net), 'text-emerald-300'], ['Écarts', data.metrics.openCases, 'text-amber-200'],
  ] : [
    ['Chauffeurs', data.metrics.drivers, 'text-blue-300'], ['En ligne', data.metrics.online, 'text-emerald-300'], ['Activités', data.metrics.activities, 'text-sky-300'], ['Transactions source', data.metrics.snapshots, 'text-violet-300'], ['Revenus bruts', money(data.metrics.gross), 'text-amber-300'], ['Taxes calculées', money(data.metrics.tax), 'text-orange-300'], ['Alertes', data.metrics.alerts, 'text-rose-300'], ['Écarts à examiner', data.metrics.openCases, 'text-amber-200'],
  ]

  return <section className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4">
      <div><div className="mb-2 flex flex-wrap items-center gap-2"><PilotDataBadge/><span className="rounded bg-qc-blue/20 px-2 py-1 text-[9px] font-bold tracking-[.13em] text-blue-200">{data.scenario.code}</span></div><p className="max-w-3xl text-xs leading-5 text-slate-300">Ce tableau Super Admin lit les enregistrements marqués <code className="rounded bg-slate-800 px-1 py-0.5 text-[10px] text-amber-200">DEMO-</code> dans Supabase. Il permet de présenter le flux complet sans les confondre avec une opération réelle.</p></div>
      <button onClick={() => void refresh()} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-xs font-semibold text-slate-300 hover:border-qc-blue"><RefreshCw size={13}/>Actualiser</button>
    </div>
    <div className={`grid gap-3 ${compact ? 'grid-cols-2 xl:grid-cols-4' : 'grid-cols-2 md:grid-cols-4 xl:grid-cols-8'}`}>{measures.map(([label, value, color]) => <div key={String(label)} className="rounded-xl border border-slate-800 bg-slate-900 p-3"><div className={`text-xl font-bold ${String(color)}`}>{String(value)}</div><div className="mt-1 text-[9px] font-bold uppercase tracking-wider text-slate-500">{String(label)}</div></div>)}</div>
    <div className={`grid gap-4 ${compact ? 'xl:grid-cols-[1.1fr_.9fr]' : 'xl:grid-cols-[1.25fr_.75fr]'}`}>
      <article className="overflow-hidden rounded-xl border border-slate-800 bg-slate-900"><div className="flex items-center justify-between border-b border-slate-800 px-4 py-3"><div className="flex items-center gap-2"><Activity size={14} className="text-qc-blue"/><h3 className="text-xs font-bold text-white">Dernières activités normalisées</h3></div><Link href="/provider-transparency" className="inline-flex items-center gap-1 text-[10px] font-semibold text-qc-blue hover:underline">Transactions <ArrowRight size={11}/></Link></div><div className="divide-y divide-slate-800">{data.activities.slice(0, compact ? 3 : 5).map((activity) => <div key={activity.id} className="flex items-center justify-between gap-3 px-4 py-3"><div className="min-w-0"><b className="block truncate text-xs text-slate-100">{activity.driver} · {clean(activity.type)}</b><span className="block truncate font-mono text-[10px] text-slate-500">{activity.id} · {activity.provider}</span></div><div className="flex shrink-0 items-center gap-3"><b className="text-xs text-emerald-300">{money(activity.net)}</b><span className={`rounded border px-1.5 py-0.5 text-[8px] font-bold ${chip(activity.reconciliation)}`}>{clean(activity.reconciliation)}</span></div></div>)}</div></article>
      <article className="rounded-xl border border-slate-800 bg-slate-900"><div className="flex items-center gap-2 border-b border-slate-800 px-4 py-3"><ShieldCheck size={14} className="text-qc-blue"/><h3 className="text-xs font-bold text-white">Contrôle pilote</h3></div><div className="space-y-3 p-4">{data.cases.length > 0 && data.cases.map((item) => <div className="rounded-lg border border-amber-400/20 bg-amber-400/5 p-3"><div className="flex justify-between gap-2"><b className="text-xs text-amber-100">Écart · {item.provider}</b><span className={`rounded border px-1.5 py-0.5 text-[8px] font-bold ${chip(item.status)}`}>{clean(item.status)}</span></div><p className="mt-1 text-[10px] leading-4 text-amber-100/70">{item.note}</p></div>)}{data.alerts.slice(0, 2).map((alert) => <div className="flex gap-2 text-[10px] text-slate-400"><AlertTriangle size={13} className="mt-0.5 shrink-0 text-amber-300"/><span><b className="text-slate-200">{clean(alert.title)}</b><br/>{alert.message}</span></div>)}{data.cases.length === 0 && data.alerts.length === 0 && <p className="text-xs text-slate-500">Aucune alerte pilote active.</p>}<Link href="/provider-transparency" className="inline-flex items-center gap-2 pt-1 text-[10px] font-bold text-qc-blue hover:underline"><Scale size={13}/>Ouvrir transparence et rapprochement</Link></div></article>
    </div>
    {!compact && <div className="grid gap-4 xl:grid-cols-3"><article className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="mb-3 flex items-center gap-2"><Database size={14} className="text-qc-blue"/><h3 className="text-xs font-bold text-white">Sources fournisseur</h3></div>{data.transactions.map((row) => <div key={row.id} className="flex justify-between border-t border-slate-800 py-2 text-[10px]"><span className="text-slate-400">{row.provider}<br/><code className="text-slate-600">{row.id}</code></span><b className="text-slate-200">{money(row.total)}</b></div>)}</article><article className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="mb-3 flex items-center gap-2"><WalletCards size={14} className="text-qc-blue"/><h3 className="text-xs font-bold text-white">Fiscalité & versements</h3></div>{data.taxRecords.map((row) => <div key={row.id} className="border-t border-slate-800 py-2 text-[10px]"><div className="flex justify-between text-slate-400"><span>{row.provider}</span><b className="text-orange-300">Δ {money(row.variance)}</b></div><span className="text-slate-600">Déclaré {money(row.providerTax)} · Calcul pilote {money(row.calculatedTax)}</span></div>)}</article><article className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="mb-3 flex items-center gap-2"><FileBarChart size={14} className="text-qc-blue"/><h3 className="text-xs font-bold text-white">Rapports pilotes</h3></div>{data.reports.map((report) => <div key={report.id} className="border-t border-slate-800 py-2 text-[10px]"><b className="block text-slate-200">{clean(report.type)}</b><span className="font-mono text-slate-600">{report.id} · {report.records} lignes</span></div>)}</article></div>}
  </section>
}
