import type { Platform, PlatformCode } from './platform.types'

export const PLATFORM_REGISTRY: Record<PlatformCode, Platform> = {
  uber: {
    id: 'plt-uber',
    code: 'uber',
    name: 'Uber',
    category: 'RIDESHARE',
    color: '#000000',
    apiEnabled: false,
    oauthSupported: true,
    webhookSupported: true,
    status: 'mock',
    documentationUrl: 'https://developer.uber.com',
    activityTypes: ['RIDE'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-24T00:00:00Z',
  },
  lyft: {
    id: 'plt-lyft',
    code: 'lyft',
    name: 'Lyft',
    category: 'RIDESHARE',
    color: '#FF00BF',
    apiEnabled: false,
    oauthSupported: true,
    webhookSupported: true,
    status: 'mock',
    documentationUrl: 'https://developer.lyft.com',
    activityTypes: ['RIDE'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-24T00:00:00Z',
  },
  doordash: {
    id: 'plt-doordash',
    code: 'doordash',
    name: 'DoorDash',
    category: 'DELIVERY',
    color: '#FF3008',
    apiEnabled: false,
    oauthSupported: false,
    webhookSupported: true,
    status: 'mock',
    documentationUrl: 'https://developer.doordash.com',
    activityTypes: ['FOOD_DELIVERY'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-24T00:00:00Z',
  },
  instacart: {
    id: 'plt-instacart',
    code: 'instacart',
    name: 'Instacart',
    category: 'GROCERY_DELIVERY',
    color: '#43B02A',
    apiEnabled: false,
    oauthSupported: true,
    webhookSupported: true,
    status: 'mock',
    documentationUrl: 'https://developer.instacart.com',
    activityTypes: ['GROCERY_DELIVERY'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-24T00:00:00Z',
  },
  ubereats: {
    id: 'plt-ubereats',
    code: 'ubereats',
    name: 'Uber Eats',
    category: 'FOOD_DELIVERY',
    color: '#06C167',
    apiEnabled: false,
    oauthSupported: true,
    webhookSupported: true,
    status: 'mock',
    documentationUrl: 'https://developer.uber.com/docs/eats',
    activityTypes: ['FOOD_DELIVERY'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-24T00:00:00Z',
  },
  skip: {
    id: 'plt-skip',
    code: 'skip',
    name: 'Skip',
    category: 'FOOD_DELIVERY',
    color: '#E31837',
    apiEnabled: false,
    oauthSupported: false,
    webhookSupported: true,
    status: 'mock',
    documentationUrl: 'https://developer.skipthedishes.com',
    activityTypes: ['FOOD_DELIVERY'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-24T00:00:00Z',
  },
  taxi: {
    id: 'plt-taxi',
    code: 'taxi',
    name: 'Taximètre',
    category: 'TAXI',
    color: '#003DA5',
    apiEnabled: true,
    oauthSupported: false,
    webhookSupported: false,
    status: 'active',
    activityTypes: ['TAXI_RIDE'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-24T00:00:00Z',
  },
  other: {
    id: 'plt-other',
    code: 'other',
    name: 'Autre plateforme',
    category: 'OTHER',
    color: '#64748B',
    apiEnabled: false,
    oauthSupported: false,
    webhookSupported: false,
    status: 'inactive',
    activityTypes: ['OTHER'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-24T00:00:00Z',
  },
}

export const PLATFORM_LIST = Object.values(PLATFORM_REGISTRY)
export const ACTIVE_PLATFORMS = PLATFORM_LIST.filter(p => p.status !== 'inactive')
