// TAXIMÈTRE.GOV — Module 31: provider revenue transparency
// Source-reported values remain separate from internal calculations and ledger entries.
import { index, numeric, pgTable, text, timestamp, uuid, varchar, boolean, integer, jsonb, date, unique } from 'drizzle-orm/pg-core'
import { providerActivities } from './provider-activities.schema'
import { providerEvents, providers } from './providers.schema'
import { driverProfiles } from './profiles.schema'
import { reconciliationCases } from './pre-db10.schema'
import { users } from './auth.schema'

export const providerTransactionSnapshots = pgTable('provider_transaction_snapshots', {
  id: uuid('id').primaryKey().defaultRandom(),
  providerId: uuid('provider_id').notNull().references(() => providers.id, { onDelete: 'restrict' }),
  providerTransactionReferenceId: uuid('provider_transaction_reference_id'),
  providerActivityId: uuid('provider_activity_id').references(() => providerActivities.id, { onDelete: 'set null' }),
  driverId: uuid('driver_id').references(() => driverProfiles.id, { onDelete: 'set null' }),
  sourceEventId: uuid('source_event_id').references(() => providerEvents.id, { onDelete: 'set null' }),
  providerTransactionId: varchar('provider_transaction_id', { length: 200 }).notNull(),
  snapshotVersion: integer('snapshot_version').notNull().default(1),
  isOriginal: boolean('is_original').notNull().default(true),
  transactionType: varchar('transaction_type', { length: 40 }),
  transactionStatus: varchar('transaction_status', { length: 40 }),
  transactionAt: timestamp('transaction_at', { withTimezone: true }),
  finalizedAt: timestamp('finalized_at', { withTimezone: true }),
  customerTotal: numeric('customer_total', { precision: 12, scale: 2 }),
  currency: varchar('currency', { length: 3 }).notNull().default('CAD'),
  jurisdictionCode: varchar('jurisdiction_code', { length: 20 }),
  sourcePayloadHash: varchar('source_payload_hash', { length: 128 }),
  sourceReceivedAt: timestamp('source_received_at', { withTimezone: true }).notNull().defaultNow(),
  sourcePayload: jsonb('source_payload').notNull().default({}),
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [unique('provider_transaction_snapshots_unique_version').on(t.providerId, t.providerTransactionId, t.snapshotVersion), index('idx_pts_provider').on(t.providerId), index('idx_pts_driver').on(t.driverId), index('idx_pts_activity').on(t.providerActivityId), index('idx_pts_source_event').on(t.sourceEventId)])

export const providerTransactionComponents = pgTable('provider_transaction_components', {
  id: uuid('id').primaryKey().defaultRandom(), transactionSnapshotId: uuid('transaction_snapshot_id').notNull().references(() => providerTransactionSnapshots.id, { onDelete: 'cascade' }), componentType: varchar('component_type', { length: 50 }).notNull(), componentCode: varchar('component_code', { length: 80 }), description: text('description'), amount: numeric('amount', { precision: 12, scale: 2 }).notNull(), currency: varchar('currency', { length: 3 }).notNull().default('CAD'), payerType: varchar('payer_type', { length: 40 }), beneficiaryType: varchar('beneficiary_type', { length: 40 }), taxable: boolean('taxable').notNull().default(false), taxType: varchar('tax_type', { length: 40 }), taxAmount: numeric('tax_amount', { precision: 12, scale: 2 }), sourceComponentId: varchar('source_component_id', { length: 200 }), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('idx_ptc_snapshot').on(t.transactionSnapshotId), index('idx_ptc_type').on(t.componentType)])

export const providerTaxRecords = pgTable('provider_tax_records', {
  id: uuid('id').primaryKey().defaultRandom(), transactionSnapshotId: uuid('transaction_snapshot_id').notNull().references(() => providerTransactionSnapshots.id, { onDelete: 'cascade' }), providerId: uuid('provider_id').notNull().references(() => providers.id, { onDelete: 'restrict' }), driverId: uuid('driver_id').references(() => driverProfiles.id, { onDelete: 'set null' }), taxType: varchar('tax_type', { length: 40 }).notNull(), jurisdictionCode: varchar('jurisdiction_code', { length: 20 }), taxableAmount: numeric('taxable_amount', { precision: 12, scale: 2 }), reportedRate: numeric('reported_rate', { precision: 12, scale: 8 }), reportedTaxAmount: numeric('reported_tax_amount', { precision: 12, scale: 2 }), governmentCalculatedAmount: numeric('government_calculated_amount', { precision: 12, scale: 2 }), varianceAmount: numeric('variance_amount', { precision: 12, scale: 2 }), reportingPeriodStart: date('reporting_period_start'), reportingPeriodEnd: date('reporting_period_end'), taxStatus: varchar('tax_status', { length: 40 }).notNull().default('REPORTED'), providerReference: varchar('provider_reference', { length: 200 }), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('idx_ptax_snapshot').on(t.transactionSnapshotId), index('idx_ptax_provider').on(t.providerId), index('idx_ptax_driver').on(t.driverId)])

export const providerTipRecords = pgTable('provider_tip_records', {
  id: uuid('id').primaryKey().defaultRandom(), transactionSnapshotId: uuid('transaction_snapshot_id').notNull().references(() => providerTransactionSnapshots.id, { onDelete: 'cascade' }), providerId: uuid('provider_id').notNull().references(() => providers.id, { onDelete: 'restrict' }), driverId: uuid('driver_id').references(() => driverProfiles.id, { onDelete: 'set null' }), tipAmount: numeric('tip_amount', { precision: 12, scale: 2 }).notNull(), currency: varchar('currency', { length: 3 }).notNull().default('CAD'), tipStatus: varchar('tip_status', { length: 40 }).notNull().default('RECEIVED'), tipReceivedAt: timestamp('tip_received_at', { withTimezone: true }), tipAdjustedAt: timestamp('tip_adjusted_at', { withTimezone: true }), tipRefundedAt: timestamp('tip_refunded_at', { withTimezone: true }), providerTipReference: varchar('provider_tip_reference', { length: 200 }), adjustmentAmount: numeric('adjustment_amount', { precision: 12, scale: 2 }).notNull().default('0'), refundAmount: numeric('refund_amount', { precision: 12, scale: 2 }).notNull().default('0'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('idx_ptip_snapshot').on(t.transactionSnapshotId), index('idx_ptip_provider').on(t.providerId), index('idx_ptip_driver').on(t.driverId)])

export const providerSettlements = pgTable('provider_settlements', {
  id: uuid('id').primaryKey().defaultRandom(), providerId: uuid('provider_id').notNull().references(() => providers.id, { onDelete: 'restrict' }), driverId: uuid('driver_id').notNull().references(() => driverProfiles.id, { onDelete: 'restrict' }), providerSettlementId: varchar('provider_settlement_id', { length: 200 }).notNull(), periodStart: timestamp('period_start', { withTimezone: true }).notNull(), periodEnd: timestamp('period_end', { withTimezone: true }).notNull(), grossCustomerAmount: numeric('gross_customer_amount', { precision: 12, scale: 2 }).notNull().default('0'), driverTransportEarnings: numeric('driver_transport_earnings', { precision: 12, scale: 2 }).notNull().default('0'), tipAmount: numeric('tip_amount', { precision: 12, scale: 2 }).notNull().default('0'), providerFeeAmount: numeric('provider_fee_amount', { precision: 12, scale: 2 }).notNull().default('0'), taxAmount: numeric('tax_amount', { precision: 12, scale: 2 }).notNull().default('0'), adjustmentAmount: numeric('adjustment_amount', { precision: 12, scale: 2 }).notNull().default('0'), refundAmount: numeric('refund_amount', { precision: 12, scale: 2 }).notNull().default('0'), totalPayable: numeric('total_payable', { precision: 12, scale: 2 }).notNull().default('0'), amountPaid: numeric('amount_paid', { precision: 12, scale: 2 }).notNull().default('0'), currency: varchar('currency', { length: 3 }).notNull().default('CAD'), settlementDate: timestamp('settlement_date', { withTimezone: true }), status: varchar('status', { length: 40 }).notNull().default('PENDING'), sourceReference: varchar('source_reference', { length: 200 }), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [unique('provider_settlements_unique_provider_ref').on(t.providerId, t.providerSettlementId), index('idx_ps_provider').on(t.providerId), index('idx_ps_driver').on(t.driverId), index('idx_ps_status').on(t.status)])

export const providerReconciliationItems = pgTable('provider_reconciliation_items', {
  id: uuid('id').primaryKey().defaultRandom(), reconciliationCaseId: uuid('reconciliation_case_id').references(() => reconciliationCases.id, { onDelete: 'set null' }), transactionSnapshotId: uuid('transaction_snapshot_id').references(() => providerTransactionSnapshots.id, { onDelete: 'set null' }), sourceAType: varchar('source_a_type', { length: 40 }).notNull(), sourceAReference: varchar('source_a_reference', { length: 200 }), sourceAAmount: numeric('source_a_amount', { precision: 12, scale: 2 }), sourceBType: varchar('source_b_type', { length: 40 }).notNull(), sourceBReference: varchar('source_b_reference', { length: 200 }), sourceBAmount: numeric('source_b_amount', { precision: 12, scale: 2 }), varianceAmount: numeric('variance_amount', { precision: 12, scale: 2 }), toleranceAmount: numeric('tolerance_amount', { precision: 12, scale: 2 }).notNull().default('0'), comparisonType: varchar('comparison_type', { length: 50 }).notNull(), resultStatus: varchar('result_status', { length: 40 }).notNull().default('PENDING'), explanation: text('explanation'), resolvedBy: uuid('resolved_by').references(() => users.id, { onDelete: 'set null' }), resolvedAt: timestamp('resolved_at', { withTimezone: true }), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('idx_pri_case').on(t.reconciliationCaseId), index('idx_pri_snapshot').on(t.transactionSnapshotId), index('idx_pri_status').on(t.resultStatus)])
