'use client'

import Link from 'next/link'
import { Activity, AlertTriangle, Car, Clock, DollarSign, FileText, RefreshCw, TrendingUp, Users, XCircle } from 'lucide-react'
import { AppShell } from '@/components/layout/AppShell'
import { Card, KpiCard } from '@/components/ui'
import { useAdminDashboard } from '@/lib/supabase/useAdminDashboard'

const money = (value: number) => new Intl.NumberFormat('fr-CA', { style: 'currency', currency: 'CAD', maximumFractionDigits: 0 }).format(value)

export default function DashboardPage() {
  const { dashboard, loading, error, refresh } = useAdminDashboard()

  return (
    <AppShell>
      <div className="mb-6 flex items-start justify-between gap-4"><div><div className="flex items-center gap-3 mb-1"><h1 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Tableau de bord</h1><span className="text-xs px-2 py-0.5 rounded-full bg-qc-blue text-white font-semibold">DONNÉES RÉELLES</span></div><p className="text-sm text-slate-500">Supervision sécurisée des chauffeurs et des activités · {dashboard ? new Date(dashboard.generatedAt).toLocaleString('fr-CA') : 'chargement'}</p></div><button onClick={() => void refresh()} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 hover:border-qc-blue dark:border-slate-700 dark:bg-slate-900"><RefreshCw size={14} />Actualiser</button></div>

      {loading ? <div className="py-20 text-center text-sm text-slate-500">Chargement des données Supabase sécurisées…</div> : error || !dashboard ? <Card className="p-6 text-center"><AlertTriangle className="mx-auto mb-3 text-orange-500" size={26} /><h2 className="font-semibold text-slate-800 dark:text-slate-100">Données administratives indisponibles</h2><p className="mt-2 text-sm text-slate-500">{error ?? 'Réessayez dans quelques instants.'}</p></Card> : <>
        <div className="mb-4"><div className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Chauffeurs</div><div className="grid grid-cols-2 md:grid-cols-5 gap-3"><KpiCard label="Total" value={dashboard.drivers.total} icon={<Users size={16} />} color="blue" /><KpiCard label="Actifs" value={dashboard.drivers.active} icon={<Users size={16} />} color="green" /><KpiCard label="En ligne" value={dashboard.drivers.online} icon={<Activity size={16} />} color="green" /><KpiCard label="Suspendus" value={dashboard.drivers.suspended} icon={<XCircle size={16} />} color="red" /><KpiCard label="En attente" value={dashboard.drivers.pending} icon={<Clock size={16} />} color="orange" /></div></div>
        <div className="mb-4"><div className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Activité aujourd’hui</div><div className="grid grid-cols-3 gap-3"><KpiCard label="Activités" value={dashboard.activity.total.toLocaleString('fr-CA')} icon={<Activity size={16} />} color="green" /><KpiCard label="Courses taxi" value={dashboard.activity.taxiTrips.toLocaleString('fr-CA')} icon={<Car size={16} />} color="blue" /><KpiCard label="Livraisons" value={dashboard.activity.deliveries.toLocaleString('fr-CA')} icon={<Car size={16} />} color="purple" /></div></div>
        <div className="mb-6"><div className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Revenus enregistrés aujourd’hui</div><div className="grid grid-cols-2 md:grid-cols-5 gap-3"><KpiCard label="Bruts" value={money(dashboard.revenue.gross)} icon={<DollarSign size={16} />} color="blue" large /><KpiCard label="Nets" value={money(dashboard.revenue.net)} icon={<TrendingUp size={16} />} color="green" large /><KpiCard label="Taxes" value={money(dashboard.revenue.tax)} icon={<DollarSign size={16} />} color="orange" /><KpiCard label="Pourboires" value={money(dashboard.revenue.tips)} icon={<DollarSign size={16} />} color="purple" /><KpiCard label="Frais" value={money(dashboard.revenue.fees)} icon={<DollarSign size={16} />} color="gray" /></div></div>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6"><Card className="lg:col-span-2 p-5"><h2 className="font-semibold text-slate-800 dark:text-slate-100">Lecture des données</h2><p className="mt-2 text-sm text-slate-500">Les indicateurs proviennent des profils chauffeur, présences et activités réellement enregistrés dans Supabase. Une base nouvellement initialisée présente naturellement des valeurs nulles jusqu’aux premières inscriptions et synchronisations.</p><div className="mt-4 grid grid-cols-3 gap-3">{[{label:'Chauffeurs actifs',value:dashboard.drivers.active},{label:'En ligne',value:dashboard.drivers.online},{label:'Activités',value:dashboard.activity.total}].map((metric) => <div key={metric.label} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><div className="text-xl font-bold text-slate-800 dark:text-white">{metric.value}</div><div className="text-[10px] text-slate-500">{metric.label}</div></div>)}</div></Card><Card className="p-5"><h2 className="font-semibold text-slate-800 dark:text-slate-100">Alertes</h2><div className={`mt-4 text-3xl font-bold ${dashboard.alerts > 0 ? 'text-orange-500' : 'text-green-600'}`}>{dashboard.alerts}</div><p className="text-xs text-slate-500 mt-1">Entrée(s) dans le registre d’alertes</p><Link href="/alerts" className="mt-4 inline-block text-xs font-semibold text-qc-blue hover:underline">Voir les alertes →</Link></Card></div>
        <Card className="mb-6 p-5"><div className="flex items-center gap-2"><FileText size={18} className="text-qc-blue" /><div><h2 className="font-semibold text-slate-800 dark:text-slate-100">Administration des comptes</h2><p className="text-xs text-slate-500">Invitez, consultez et supervisez les administrateurs autorisés.</p></div><Link href="/admin/users" className="ml-auto text-xs font-semibold text-qc-blue hover:underline">Gérer les administrateurs →</Link></div></Card>
      </>}
    </AppShell>
  )
}
